export const EXPAND_MENU = 'EXPAND_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const TOGGLE_DEV = 'TOGGLE_DEV';
export const TOGGLE_GRID = 'TOGGLE_GRID';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_CLEAR_ERROR = 'LOGIN_USER_CLEAR_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';

// Profile
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

export const CURRENT_SELECTION_SUCCESS = 'CURRENT_SELECTION_SUCCESS';
export const CURRENT_SELECTION_ERROR = 'CURRENT_SELECTION_ERROR';
export const CURRENT_SELECTION_CREATE = 'CURRENT_SELECTION_CREATE';
export const CURRENT_SELECTION_UPDATE = 'CURRENT_SELECTION_UPDATE';
export const CURRENT_SELECTION_FETCH = 'CURRENT_SELECTION_FETCH';
export const CURRENT_SELECTION_DELETE = 'CURRENT_SELECTION_DELETE';

export const SELECTIONS_LIST_ERROR = 'SELECTIONS_LIST_ERROR';
export const SELECTIONS_LIST_FETCH = 'SELECTIONS_LIST_FETCH';
export const SELECTIONS_LIST_SUCCESS = 'SELECTIONS_LIST_SUCCESS';

export const ITEM_CREATE = 'ITEM_CREATE';
export const ITEM_UPDATE = 'ITEM_UPDATE';
export const ITEM_ERROR = 'ITEM_ERROR';
export const ITEM_FETCH = 'ITEM_FETCH';
export const ITEM_DELETE = 'ITEM_DELETE';
export const ITEM_SELECTED = 'ITEM_SELECTED';

export const SELECT_ITEM_FETCH = 'SELECT_ITEM_FETCH';
export const SELECT_ITEM = 'SELECT_ITEM';

export const TRACKER_CREATE = 'TRACKER_CREATE,';
export const TRACKER_UPDATE = 'TRACKER_UPDATE,';
export const TRACKER_ERROR = 'TRACKER_ERROR,';
export const TRACKER_FETCH = 'TRACKER_FETCH,';
export const TRACKER_DELETE = 'TRACKER_DELETE';

export const PROGRAM_CREATE = 'PROGRAM_CREATE';
export const PROGRAM_UPDATE = 'PROGRAM_UPDATE';
export const PROGRAM_ERROR = 'PROGRAM_ERROR';
export const PROGRAM_FETCH = 'PROGRAM_FETCH';
export const PROGRAM_DELETE = 'PROGRAM_DELETE';
export const PROGRAM_SELECTED = 'PROGRAM_SELECTED';
export const PROGRAM_SET_EDIT = 'PROGRAM_SET_EDIT';
export const PROGRAM_SET_DEFAULT = 'PROGRAM_SET_DEFAULT';
export const PROGRAM_ACTIVE_CREATE = 'PROGRAM_ACTIVE_CREATE';

/* Sessions */
export const SESSION_CREATE = 'SESSION_CREATE';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_ERROR = 'SESSION_ERROR';
export const SESSION_FETCH = 'SESSION_FETCH';
export const SESSION_DELETE = 'SESSION_DELETE';
export const SESSION_SELECTED = 'SESSION_SELECTED';
export const SESSION_SET_EDIT = 'SESSION_SET_EDIT';

export const EXPAND_SIDEMENU = 'EXPAND_SIDEMENU';
export const SET_OVERLAY = 'SET_OVERLAY';
export const CONTROLS_SET_ACTION_PANEL = 'CONTROLS_SET_ACTION_PANEL';

export default {
  EXPAND_MENU,
  CLOSE_MENU,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAIL,
  LOGIN_USER,
  LOGIN_WITH_PROVIDER_FIREBASE,
  REGISTER_FIREBASE_USER,
  LOGIN_FIREBASE_USER,
  FETCH_FIREBASE_USER,
  UPDATE_FIREBASE_USER,
  CHANGE_FIREBASE_USER_PASSWORD,
  FIREBASE_PASSWORD_RESET_EMAIL,
  LOGOUT_FIREBASE_USER,
  CURRENT_SELECTION_SUCCESS,
  CURRENT_SELECTION_ERROR,
  CURRENT_SELECTION_CREATE,
  CURRENT_SELECTION_UPDATE,
  CURRENT_SELECTION_FETCH,
  CURRENT_SELECTION_DELETE,
  SELECTIONS_LIST_ERROR,
  SELECTIONS_LIST_FETCH,
  SELECTIONS_LIST_SUCCESS,
  TOGGLE_DEV,
  TOGGLE_GRID
};
